# -*- coding: utf-8 -*-
"""Optimización de Ventas y Análisis ABC (E-commerce)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XxfWiqiHRz0RXb_94Y99niQ5ntaLEKKM

**Paso 1: Carga y "Tuneo" en Python (Colab)**
"""

import pandas as pd

# 1. Cargar el dataset (ajusta el nombre si es .xlsx o .csv)
df = pd.read_csv('SampleSuperstore.csv', encoding='windows-1252')

# 2. Traducir columnas clave para que tu Dashboard sea profesional en español
columnas_es = {
    'Ship Mode': 'Metodo_Envio',
    'Segment': 'Segmento',
    'Country': 'Pais',
    'City': 'Ciudad',
    'State': 'Estado',
    'Region': 'Region',
    'Category': 'Categoria',
    'Sub-Category': 'Subcategoria',
    'Sales': 'Ventas',
    'Quantity': 'Cantidad',
    'Discount': 'Descuento',
    'Profit': 'Ganancia'
}
df.rename(columns=columnas_es, inplace=True)

# 3. Crear una métrica crítica: Margen de Ganancia (%)
# Esto es lo que los gerentes realmente miran
df['Margen_Porcentaje'] = (df['Ganancia'] / df['Ventas']) * 100

# 4. Asegurar traducción y convertir fechas
if 'Order Date' in df.columns:
    df.rename(columns={'Order Date': 'Fecha_Pedido'}, inplace=True)

# Verificar si la columna existe antes de convertir
if 'Fecha_Pedido' in df.columns:
    df['Fecha_Pedido'] = pd.to_datetime(df['Fecha_Pedido'])
    print("Columna 'Fecha_Pedido' convertida exitosamente.")
else:
    print("Error: No se encontró 'Fecha_Pedido' ni 'Order Date'. Revisa el Paso 1.")

# Guardar para Power BI
df.to_csv('Superstore_Limpio.csv', index=False)

"""**Paso 2: Análisis de Pérdidas**"""

# Identificar productos con Ganancia Negativa
productos_en_perdida = df[df['Ganancia'] < 0].groupby('Subcategoria')['Ganancia'].sum().sort_values()

print("Subcategorías que más dinero pierden:")
print(productos_en_perdida.head())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Supongamos que tu dataframe se llama 'df' y ya tiene las columnas traducidas
# 1. Filtrar solo las ventas con pérdida
df_perdidas = df[df['Ganancia'] < 0].copy()

# 2. Agrupar por Subcategoría para ver quién es el "agujero negro" de dinero
resumen_perdidas = df_perdidas.groupby('Subcategoria').agg({
    'Ganancia': 'sum',
    'Ventas': 'sum',
    'Descuento': 'mean' # Promedio de descuento aplicado
}).sort_values(by='Ganancia')

print("Análisis de Subcategorías en Pérdida:")
print(resumen_perdidas)

# 3. Visualización de la relación Descuento vs Ganancia
plt.figure(figsize=(10,6))
sns.scatterplot(data=df, x='Descuento', y='Ganancia', hue='Categoria', alpha=0.5)
plt.axhline(0, color='red', linestyle='--')
plt.title('Impacto de los Descuentos en la Ganancia')
plt.show()